### PR TITLE
Update now.json

### PR DESCRIPTION
**Pull request by franciscolourenco**

### CODE REVIEW

**Comment by dariye** [comment]
Don't have time to test this now but I'll test and merge it all looks good. I think we may need to specify a builder. 

Thanks for your contribution!!!

**Comment by franciscolourenco** [comment]
The deployment is working, I just tested. Feel free to merge.

**Comment by dariye** [comment]
Sorry, I've been preoccupied and never got time to look at this. Actually just made a repo that would be perfect to test this with. As soon as I test this, I'll merge it. ~I don't have a contributors section yet on the readme but do you think you could create one on the readme~ @franciscolourenco ?

**Comment by dariye** [comment]
Hey @franciscolourenco, I hope you're having a pleasant weekend. I tested your pr and everything works fine. Next up is just updating the README with the information on how to [add `now` secrets](https://zeit.co/docs/v2/build-step). Since you get this error if you run it without prior knowledge.
Screenshot 2019-08-25 at 11 38 39

**Comment by franciscolourenco** [comment]
I've added the commands to the script. It's still missing general information about how to get the values and configure the webhook. Maybe we should at least link to the blog post?

**Comment by dariye** [comment]
Fair. The blog post is linked. Maybe we may just need to copy the instructions for general setup to the readme so people don't have to visit the blog post. I'll merge this now and we can add that later

**Comment by dariye** [comment]
@all-contributors please add @franciscolourenco for code and doc

**Pull request merged**
